apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx
spec: # specification for the deoloyment
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: # specification for pods
      containers:
        - name: nginx
          image: nginx:1.27.2-alpine-slim
          ports:
            - containerPort: 8080
