apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_USER: cGd1c2VybmFtZQ==   # echo -n "pgusername" | base64)
  DB_PASSWORD: cGdwYXNzd29yZA== # echo -n "pgpassword" | base64)
